#!/bin/bash

BASEPATH=/home/damien/homeserv/;
SOURCEDIR=damien@192.168.1.116:office/;
BACKUPCOUNT=10;

BACKUPDIR=${BASEPATH}office-backup/;

#Make directories if they don't already exist
mkdir -p $BACKUPDIR

rsync -avz -e ssh ${SOURCEDIR} ${BACKUPDIR}
