#!/bin/bash

BASEPATH=/home/damien/homeserv/;
SOURCEDIR=damien@192.168.1.116:office/;
BACKUPCOUNT=10;

BACKUPDIR=${BASEPATH}office-backup/;
ARCHIVEDIR=${BASEPATH}archive/;

#Make directories if they don't already exist
mkdir -p $BACKUPDIR
mkdir -p $ARCHIVEDIR

#Sync before archive
rsync -avz -e ssh ${SOURCEDIR} ${BACKUPDIR}
RETVAL=$?
if [ $RETVAL -eq 0 ];
then
    #Remove oldest file if backup count reached
    FILECOUNT=$(ls | wc -l);
    if [ $FILECOUNT -ge $BACKUPCOUNT ]
    then
        rm -f ${ARCHIVEDIR}$(ls -tr ${BASEPATH}/archive | head -n 1);
        echo "REMOVED OLDEST FILE";
    fi

    #Archive
    sudo tar -cvzf ${ARCHIVEDIR}$(date +%Y%m%d).tar.gz ${BACKUPDIR};
    RETVAL=$?
    if [ $RETVAL -eq 0 ];
    then
        #Remove all deleted files
        rsync -avz -e ssh ${SOURCEDIR} ${BACKUPDIR} --delete
        echo "SUCCESS";
    fi
fi
