#!/bin/bash

BASEPATH=/home/damien/homeserv/;
SOURCEDIR=damien@192.168.1.116:office/;
BACKUPCOUNT=10;

BACKUPDIR=${BASEPATH}office-backup/;
ARCHIVEDIR=${BASEPATH}archive/;

BASELOG="Weekly sync and archive on ($(date +%Y-%m-%d)): "

#Make directories if they don't already exist
mkdir -p $BACKUPDIR
mkdir -p $ARCHIVEDIR
touch ${BASEPATH}/log.txt;
touch ${BASEPATH}/rsync.log;

#Sync before archive
rsync -avz -e ssh ${SOURCEDIR} ${BACKUPDIR}
RETVAL=$?
if [ $RETVAL -eq 0 ];
then
    #Remove oldest file if backup count reached
    FILECOUNT=$(ls | wc -l);
    if [ $FILECOUNT -ge $BACKUPCOUNT ]
    then
        rm -f ${ARCHIVEDIR}$(ls -tr ${BASEPATH}/archive | head -n 1);
        echo ${BASELOG}REMOVED OLDEST FILE;
    fi

    #Archive
    tar -cvzf ${ARCHIVEDIR}$(date +%Y%m%d).tar.gz ${BACKUPDIR};
    RETVAL=$?
    if [ $RETVAL -eq 0 ];
    then
        #Remove all deleted files
        rsync -avz -e ssh ${SOURCEDIR} ${BACKUPDIR} --delete
        RETVAL=$?
        if [ $RETVAL -eq 0 ];
        then
            echo ${BASELOG}SUCCESS >> ${BASEPATH}/log.txt;
        else
            echo ${BASELOG}FAILED DELETED FILES CLEAN UP >> ${BASEPATH}/log.txt;
        fi
    else
        echo ${BASELOG}FAILED ARCHIVE >> ${BASEPATH}/log.txt;
    fi
else
    echo ${BASELOG}FAILED SYNC >> ${BASEPATH}/log.txt;
fi
